Tienda/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Tienda.Models

{
    public enum Categoria
    {
        Ficcion,
        Drama,
        Comedia,
        Horrir

    }

    public class Pelicula{
    
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage= "EL campo {0} es requerido")]
        [StringLength(80, MinimumLength = 5, ErrorMessage= "El {0} debe ser de al menos {2} caracteres.")]
        [Display(Name = "Nombre de la pelicula")]
        public string titulo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }
        public string Director { get; set; }
        public Categoria? categoria {get; set;}
        public string ruta { get; set; }
        public decimal precio { get; set; }
        [StringLength(500, MinimumLength = 5,
            ErrorMessage = "El {0} debe ser de al menos {2} Caracteres.")]
        public string description { get; set; }
        public int Rate { get; set; }
    }
}

Tienda/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tienda.Models;
using PagedList;
using System.IO;

namespace Tienda.Controllers
{
    public class PeliculasController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        // GET: Peliculas
        private int paginacion = 10;
        
        public ActionResult Index(int pagina = 1)
        {
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult Lista(int pagina = 1)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Resultados", db.peliculas.ToList().ToPagedList(pagina, paginacion));            
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult ListaImagenes(int pagina = 1)
        {
            var paginacion = 18;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ResultadosImagenes", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }


        // GET: Peliculas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titulo,Fecha,Director,categoria,ruta,precio,description")] Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);

                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }

                db.peliculas.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titulo,Fecha,Director,categoria,ruta,precio,description")] Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);

                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            db.peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RateProduct(int id, int rate)
        {

            int userId = 142;
            bool success = false;
            string error = "";
            try
            {
                success = CalificarPelicula(userId, id, rate);
            }
            catch (System.Exception ex)
            {
                error = ex.Message;
            }
            return Json(new { error = error, success = success, pid = id },
                JsonRequestBehavior.AllowGet);

        }

        private bool CalificarPelicula(int userId, int id, int rate)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return false;
            }
            pelicula.Rate = rate;
            db.Entry(pelicula).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tienda/Views/Peliculas/Create.cshtml
@model Tienda.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Peliculas",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.categoria, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="previewImg"
                     width="100px" height="100px" />
                @Html.ValidationMessageFor(model => model.ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                imagen:
            </div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src',
                        e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

Tienda/Views/Peliculas/Delete.cshtml
@model Tienda.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tienda/Views/Peliculas/Details.cshtml
@model Tienda.Models.Pelicula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ruta)*@

            <img title="@Model.titulo" src="@Url.Content("~" + Model.ruta)"
                 width="100px" height="100px" />

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            Rate
        </dt>

        <dd>
            <span id="spanRate">
            @Html.DisplayFor(model => model.Rate)
            </span>
            @Html.Partial("_Rating", Model)
            @Html.HiddenFor(m => m.Rate, new { id = "Rate" })
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts{
    <script src="@Url.Content("~/Scripts/rating.js")"></script>
    <script>
        $(document).ready(function () {
            var pid = $("#Rate").val();
            $("input[type=radio][value='" + pid + "']").attr('checked', 'checked');

        });

        $(function () {
            $('.ratting-item').rating(function (vote, event) {
                var anchor = $(event.currentTarget);
                var pid = anchor.closest(".ratting-item").data("pid");
                var url = '@Url.Action("RateProduct", "Peliculas")';
                $("#Rate").val(vote);
                $("#spanRate").text(vote);

                $('.ratting-item[data-pid=' + pid + ']')
                    .next()
                    .text("Actualizando Calificacion...");

                var request = $.ajax({
                    url: url,
                    type: "GET",
                    data: { rate: vote, id: pid }
                });

                request.success(function (msg) {
                    console.log("sucess: " + msg);
                    if (msg.success) {
                        $('.result').text("Listo");
                    }
                });

                request.error(function (msg) {
                    console.log("error:" + msg);
                    $('.result').text(msg);
                });

                request.complete(function () {
                    //console.log("complete");
                    //$('.ratting-item[data-pid=' + pid + ']')
                    //.next()
                    //.text("");
                });

            });

        });
    </script>
}

Tienda/Views/Peliculas/Edit.cshtml
@model Tienda.Models.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Peliculas",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.categoria, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ruta, new { htmlAttributes = new { @class = "form-control" } })
                <img id="previewImg" title="@Model.titulo" src="@Url.Content("~" + Model.ruta)"
                     width="100px" height="100px" />
                @Html.ValidationMessageFor(model => model.ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                imagen:
            </div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src',
                        e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

Tienda/Views/Peliculas/Index.cshtml
@using PagedList.Mvc

@model PagedList.IPagedList<Tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager1" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Index",
        new {pagina}),
        PagedListRenderOptions.MinimalWithItemCountText
    )
</div>
<div id="peliculas">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoria)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ruta)*@
                <img title="@item.titulo" src="@Url.Content("~" + item.ruta)"
                     width="100px" height="100px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
}

    </table>
</div>

Tienda/Views/Peliculas/Lista.cshtml
@using PagedList.Mvc

@model PagedList.IPagedList<Tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager1" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Lista",
        new { pagina }),
        PagedListRenderOptions.MinimalWithItemCountText
    )
</div>



@Html.Partial("_Resultados", Model)



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tienda/Views/Peliculas/ListaImagenes.cshtml
@using PagedList.Mvc

@model PagedList.IPagedList<Tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}
<div class="container">
   

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>



@Html.Partial("_ResultadosImagenes", Model)


</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tienda/Views/Peliculas/_Resultados.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Tienda.Models.Pelicula>


<div id="peliculas">

    pager ajax
    <div class="pagedList" data-otf-target="#peliculas">
        @Html.PagedListPager(list: Model,
    generatePageUrl: page => Url.Action("Lista", new { pagina = page }),
                                             options: PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
                                             {
                                                 HttpMethod = "GET",
                                                 UpdateTargetId = "peliculas"
                                             }))

    </div>

    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Director)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoria)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ruta)*@
                    <img title="@item.titulo" src="@Url.Content("~" + item.ruta)"
                         width="100px" height="100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
</div>

Tienda/Views/Peliculas/_ResultadosImagenes.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Tienda.Models.Pelicula>


<div id="peliculas">

    pager ajax
    <div class="pagedList" data-otf-target="#peliculas">
        @Html.PagedListPager(list: Model,
    generatePageUrl: page => Url.Action("ListaImagenes", new { pagina = page }),
                                             options: PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
                                             {
                                                 HttpMethod = "GET",
                                                 UpdateTargetId = "peliculas"
                                             }))

    </div>


    <ul id="album-list">
        @foreach (var pel in Model)
        {
            <li>
                <a href="@Url.Action("Details", new { id = pel.id })">
                    <img alt="@pel.titulo" title="@pel.titulo" src="@Url.Content("~" + pel.ruta)"
                         width="100px" height="100px" />
                </a>
                <span>@pel.titulo</span>
            </li>

        }
    </ul>
</div>